swagger: "2.0"
info:
  description: "This is a swagger for an initiative O.G.O idea genie portal"
  version: "1.0.0"
  title: "Swagger Idea genie"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "sreenadh1543@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/idea-genie"
schemes:
- "https"
paths:
  /user/register:
    post:
      tags:
      - "Register"
      summary: "Add a new user to the idea-genie Portal"
      description: "Operation to register new user to idea genie portal"
      operationId: "addUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New user added to idea-genie portal"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "201":
          description: "Created Ok"
        "500":
          description: "Service Response"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  User:
    type: "object"
    properties:
      emailId:
        type: "string"
        description: "Email id provided by user for registration"
        pattern: '^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$'
      password:
        description: "Password provided by user for registration"
        type: "string"
        pattern: "^[ A-Za-z0-9_@./#&+-]*$"
      firstName:
        type: "string"
        pattern: "^[ A-Za-z0-9]*$"
        description: "First Name provided by user for registration"
      lastName:
        type: "string"
        pattern: "^[ A-Za-z0-9]*$"
        description: "Last Name provided by user for registration"
      mobileNumber:
        type: "string"
        pattern: "^[ 0-9+]*$"
        description: "Mobile Number provided by user for registration"
      skills:
        description: "Skills provided by user for registration"
        type: "array"
        items:
          type: "string"
          pattern: "^[ A-Za-z0-9]*$"
      preferredRoles:
        description: "Preferred roles provided by user for registration"
        type: "array"
        items:
          type: "string"
          pattern: "^[ A-Za-z0-9]*$"
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "string"
      message:
        type: "string"